2020-02-14 11:01:36,940 ERROR: Exception on /search [GET] [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/main/routes.py", line 147, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/models.py", line 89, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/search.py", line 24, in query_index
    'from': (page - 1) * per_page, 'size': per_page}
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1548, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-02-17 06:33:32,430 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 03:53:29,968 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 04:29:18,333 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 04:29:26,604 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 06:59:43,693 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 07:01:24,617 ERROR: Exception on /index [POST] [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/main/routes.py", line 35, in index
    db.session.commit()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 510, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/models.py", line 121, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/search.py", line 7, in add_to_index
    for field in model.__search__:
AttributeError: 'Post' object has no attribute '__search__'
2020-02-20 07:05:25,953 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 07:05:33,008 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 07:06:02,659 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
2020-02-20 07:06:07,903 ERROR: Exception on / [POST] [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/main/routes.py", line 35, in index
    db.session.commit()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 510, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/envf/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/models.py", line 121, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "/Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/search.py", line 7, in add_to_index
    for field in model.__search__:
AttributeError: 'Post' object has no attribute '__search__'
2020-02-20 07:09:02,822 INFO: Microblog startup [in /Volumes/Work/Flask_test/Flask_Mega_Tutorial/Flask_mega/app/__init__.py:79]
